# Generated by Django 4.0.5 on 2023-03-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('position', models.CharField(default='False', max_length=1000)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Denee.login')),
                ('admin_name', models.CharField(max_length=1000)),
                ('admin_mobileNumber', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=1000)),
                ('admin_address', models.CharField(max_length=10000)),
                ('admin_detailsOfWorkAndWorking', models.CharField(max_length=10000)),
                ('admin_registrationNumber', models.CharField(max_length=200)),
                ('admin_image', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('doner_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Denee.login')),
                ('doner_name', models.CharField(max_length=1000)),
                ('doner_mobileNumber', models.CharField(max_length=200)),
                ('doner_email', models.CharField(max_length=1000)),
                ('doner_address', models.CharField(max_length=10000)),
                ('doner_adharcardNumber', models.CharField(max_length=200)),
                ('doner_image', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'db_table': 'doner',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('recipt_image', models.CharField(max_length=10000, null=True)),
                ('admin_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Denee.admin')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('recipt_image', models.CharField(max_length=10000, null=True)),
                ('admin_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Denee.admin')),
                ('doner_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Denee.doner')),
            ],
            options={
                'db_table': 'donation',
            },
        ),
    ]
