# Generated by Django 4.0.5 on 2023-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recipt_image',
            new_name='event_banerImage',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Coming', max_length=100),
        ),
    ]
