# Generated by Django 4.0.5 on 2023-04-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denee', '0002_rename_recipt_image_event_event_banerimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='salt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
