# Generated by Django 4.0.5 on 2023-04-01 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Denee', '0003_login_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='active',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
